// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUC5ZfYzanMxE6360Ns8UqhLjJ2cKJ52I',
    appId: '1:234400440674:web:ce627b03a5aa8efb780c3b',
    messagingSenderId: '234400440674',
    projectId: 'social-media-app-6677d',
    authDomain: 'social-media-app-6677d.firebaseapp.com',
    storageBucket: 'social-media-app-6677d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4CcEOkgCw_8XGyeZn1XQhb2-iGgAJ0vk',
    appId: '1:234400440674:android:7fe10f75f7bfd9fa780c3b',
    messagingSenderId: '234400440674',
    projectId: 'social-media-app-6677d',
    storageBucket: 'social-media-app-6677d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsNlHsNZ0q8uvasB5KVoU8mdT3vPjti2Y',
    appId: '1:234400440674:ios:9034a58a1cb1e2db780c3b',
    messagingSenderId: '234400440674',
    projectId: 'social-media-app-6677d',
    storageBucket: 'social-media-app-6677d.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsNlHsNZ0q8uvasB5KVoU8mdT3vPjti2Y',
    appId: '1:234400440674:ios:9034a58a1cb1e2db780c3b',
    messagingSenderId: '234400440674',
    projectId: 'social-media-app-6677d',
    storageBucket: 'social-media-app-6677d.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUC5ZfYzanMxE6360Ns8UqhLjJ2cKJ52I',
    appId: '1:234400440674:web:de6e4ef7212d92ef780c3b',
    messagingSenderId: '234400440674',
    projectId: 'social-media-app-6677d',
    authDomain: 'social-media-app-6677d.firebaseapp.com',
    storageBucket: 'social-media-app-6677d.firebasestorage.app',
  );
}
